project:
  type: website

website:
  title: "Personal_Blog_Isamar"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/isamar-sampayo-036276139/
      - icon: github
        href: https://github.com/IsaE2411
      - icon: twitter
        href: https://x.com/isapsam
format:
  html:
    theme: quartz
    css: styles.css
editor: visual

comments: 
  giscus: 
    repo: IsaE2411/Personal_Blog_ISamar
    



