project:
  type: website

website:
  title: "Personal_Blog_Isamar"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: quartz
    css: styles.css
editor: visual

comments: 
  giscus: 
    repo: IsaE2411/Personal_Blog_ISamar
    



